download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-asa-5.0.1.tar.gz
format_version: 1.0.0
name: asa
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/asa/versions/5.0.1/
