download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-ucs-1.10.0.tar.gz
format_version: 1.0.0
name: ucs
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.10.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/ucs/versions/1.10.0/
