download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-ios-8.0.0.tar.gz
format_version: 1.0.0
name: ios
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 8.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/ios/versions/8.0.0/
